# -*- coding: utf-8 -*-
"""6 Dummy variables.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EJRYVZNjMK5C92u9cL--RWTF9VbRp9j2
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

import io
data= pd.read_csv(io.BytesIO(uploaded['homeprices.csv']))

data

pd.get_dummies(data.town)

dum = pd.get_dummies(data.town)

merged = pd.concat([data,dum],axis = 'columns')
merged

final = merged.drop(['town','west windsor'],axis = 'columns')
 final

from sklearn.linear_model import LinearRegression
model = LinearRegression()

X = final.drop('price',axis = 'columns')
X

y = final.price
y

model.fit(X,y)

model.predict([[2800,0,1]])

model.score(X,y)

data

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

dfle = data
dfle.town = le.fit_transform(dfle.town)
dfle

X =dfle[['town','area']].values
X

y = dfle.price
y

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town',OneHotEncoder(),[0])],remainder = 'passthrough')

X= ct.fit_transform(X)
X

