# -*- coding: utf-8 -*-
"""7 Training and testing data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-IneIuOtKAxY_i_cZCo87be5nPeJj3Hl
"""

import pandas as pd
import matplotlib.pyplot as plt

!git clone 'https://github.com/sachinkavindaa/Machine-learning-with-Python'

df = pd.read_csv('/content/Machine-learning-with-Python/ML/7 Training and testing data/carprices.csv')
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.scatter(df['Mileage'],df['Sell Price($)'])

plt.scatter(df['Age(yrs)'],df['Sell Price($)'])

X = df[['Mileage','Age(yrs)']]
y = df['Sell Price($)']

X

y

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size = 0.2)

X_train
len(X_train)

len(X_test)

from sklearn.linear_model import LinearRegression
clf = LinearRegression()

clf.fit(X_train,y_train)

clf.predict(X_test)

y_test

clf.score(X_test,y_test)

