# -*- coding: utf-8 -*-
"""Exe_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SCtGljj4rvg06AF2cN5fcb1XTHMbDiuQ
"""

import pandas as pd
from matplotlib import pyplot as plt

!git clone 'https://github.com/sachinkavindaa/Machine-learning-with-Python'

df = pd.read_csv('/content/Machine-learning-with-Python/ML/8 Logestic regression/HR_comma_sep.csv')
df

#Average numbers for all columns

df.groupby('left').mean()

pd.crosstab(df.salary,df.left).plot(kind='bar')

pd.crosstab(df.Department,df.left).plot(kind='bar')

subdf = df[['satisfaction_level','average_montly_hours','promotion_last_5years','salary']]
subdf

salary_dummies = pd.get_dummies(subdf.salary, prefix="salary")

df_with_dummies = pd.concat([subdf,salary_dummies],axis='columns')

df_with_dummies.head()

df_with_dummies.drop('salary',axis='columns',inplace=True)
df_with_dummies.head()

X = df_with_dummies
X.head()

y = df.left

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.3)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

model.fit(X_train, y_train)

model.predict(X_test)

model.score(X_test,y_test)

